# Generated by Django 3.0.6 on 2020-05-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_auto_20200519_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
