# Generated by Django 3.0.6 on 2020-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='CIN',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='business',
            name='DGFT',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='business',
            name='GST',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='business',
            name='PAN',
            field=models.CharField(default='', max_length=13),
        ),
    ]
