# Generated by Django 3.0.6 on 2020-05-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name',
        ),
        migrations.DeleteModel(
            name='Sub_Categories',
        ),
    ]
