# Generated by Django 3.0.6 on 2020-05-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_auto_20200522_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.FileField(default='', upload_to='Pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sub_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=None)),
                ('sub_categories', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Categories.Categories')),
            ],
        ),
    ]
